# Generated by Django 5.2.4 on 2025-07-17 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('books', 'Books'), ('clothing', 'Clothing'), ('food', 'Food'), ('furniture', 'Furniture'), ('home_appliance', 'Home Aplliance'), ('kitchenware', 'Kitchenware'), ('office_supplies', 'Office Supplies'), ('personal_hygiene', 'Personal Hygiene'), ('toys_and_games', 'Toys and Games'), ('other', 'Other')], default='others', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='items/')),
                ('created_at', models.TimeField(auto_now_add=True)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
    ]
