# Generated by Django 5.2.4 on 2025-07-19 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('iso', models.CharField(max_length=2)),
                ('name', models.TextField(max_length=100)),
                ('nicename', models.TextField(max_length=100)),
                ('iso3', models.CharField(max_length=3, null=True)),
                ('numcode', models.IntegerField(null=True)),
                ('phonecode', models.IntegerField()),
            ],
            options={
                'db_table': 'countries',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('region_name', models.TextField(max_length=100, unique=True)),
                ('region_code', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'regions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('books', 'Books'), ('clothing', 'Clothing'), ('electronic', 'Electronic'), ('food', 'Food'), ('furniture', 'Furniture'), ('home_appliance', 'Home Appliance'), ('kitchenware', 'Kitchenware'), ('office_supplies', 'Office Supplies'), ('personal_hygiene', 'Personal Hygiene'), ('shoes', 'Shoes'), ('toys_and_games', 'Toys and Games'), ('other', 'Other')], default='other', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='items/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('available', models.BooleanField(default=True)),
                ('street', models.CharField(blank=True, max_length=255, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tupie_app.region')),
            ],
        ),
    ]
