# Generated by Django 5.2.4 on 2025-07-17 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tupie_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('books', 'Books'), ('clothing', 'Clothing'), ('food', 'Food'), ('furniture', 'Furniture'), ('home_appliance', 'Home Aplliance'), ('kitchenware', 'Kitchenware'), ('office_supplies', 'Office Supplies'), ('personal_hygiene', 'Personal Hygiene'), ('toys_and_games', 'Toys and Games'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
