# Generated by Django 5.2.4 on 2025-08-09 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tupie_app', '0002_remove_item_image_itemimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='items/'),
        ),
        migrations.AlterField(
            model_name='itemimage',
            name='image',
            field=models.ImageField(default='jvjving.com.png', upload_to='items/extra/'),
            preserve_default=False,
        ),
    ]
