# Generated by Django 5.2.4 on 2025-07-26 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tupie_app', '0002_itemrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('beverages', 'Beverages'), ('books', 'Books'), ('clothing', 'Clothing'), ('electronic', 'Electronic'), ('food', 'Food'), ('furniture', 'Furniture'), ('home_appliance', 'Home Appliance'), ('kitchenware', 'Kitchenware'), ('office_supplies', 'Office Supplies'), ('personal_hygiene', 'Personal Hygiene'), ('shoes', 'Shoes'), ('toys_and_games', 'Toys and Games'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='verification_status',
            field=models.CharField(choices=[('unverified', 'Unverified'), ('verified', 'Verified User'), ('organization', 'Verified Organization'), ('administrator', 'Administrator')], default='unverified', max_length=20),
        ),
    ]
