# Generated by Django 5.2.4 on 2025-08-09 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tupie_app', '0003_item_main_image_alter_itemimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='main_image',
        ),
        migrations.AlterField(
            model_name='itemimage',
            name='image',
            field=models.ImageField(upload_to='items/'),
        ),
    ]
