# Generated by Django 5.2.4 on 2025-08-02 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tupie_app', '0003_conversation_message_conversation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='conversation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='tupie_app.conversation'),
            preserve_default=False,
        ),
    ]
