# Generated by Django 5.2.4 on 2025-08-09 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tupie_app', '0004_remove_item_main_image_alter_itemimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image1',
            field=models.ImageField(default='logo.png', upload_to='items/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='items/'),
        ),
        migrations.AddField(
            model_name='item',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='items/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tupie_app.district'),
        ),
        migrations.AlterField(
            model_name='item',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tupie_app.place'),
        ),
        migrations.AlterField(
            model_name='item',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tupie_app.region'),
        ),
        migrations.AlterField(
            model_name='item',
            name='ward',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tupie_app.ward'),
        ),
    ]
